image: maven

default:
  tags:
    - common

stages:
  - validate
  - build
  - test
  - package

Validate job:
  stage: validate
  script: mvn validate

Build job:
  stage: build
  script:
    - mvn compile

Test job:
  stage: test
  script:
    - mvn test
  artifacts:
    when: always
    paths:
      - back/target/surefire-reports/*.xml
      - back/target/site/jacoco
    reports:
      junit: back/target/surefire-reports/*.xml
  coverage: /Total.*?([0-9]{1,3})%/

Package job:
  stage: package
  script: mvn package
  artifacts:
    when: always
    paths:
      - target/bankSystem-1.0.0-jar-with-dependencies.jar